sudo: false
language: haskell
ghc: 8.0.2

matrix:
    include:

        # Linux
        - env: TARGET=x86_64-unknown-linux-gnu

        # OS X
        - env: TARGET=x86_64-apple-darwin
          os: osx

before_install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal new-build --dependencies-only -w ghc-8.0.2

install:
- cabal new-build -w ghc-8.0.2
- cp $(find -name madlang -executable | tail -n1) $HOME/.cabal/bin

script:
- madlang run demo/shakespeare.mad
- cabal new-test -w ghc-8.0.2
- cabal new-bench -w ghc-8.0.2
