---
sudo: false
cache:
  directories:
    - $HOME/.stack
    - $HOME/.madlang
addons:
  apt:
    packages:
      - libgmp3-dev
matrix:
  include:

    # Linux
    - env: TARGET=x86_64-unkown-linux-gnu
      language: python

    # OS X
    - env: TARGET=x86_64-apple-darwin
      os: osx
      language: default

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - |
    if [ `uname` = "Linux" ]
    then
      yamllint stack.yaml
      yamllint appveyor.yml
      yamllint .travis.yml
      yamllint .hlint.yaml
      yamllint .stylish-haskell.yaml
      yamllint .weeder.yaml
    else
      echo "skipping yaml verification..."
    fi
  - stack --no-terminal build --haddock --no-haddock-deps --copy-bins
  - stack test --no-terminal
  - stack bench --no-terminal --no-run-benchmarks
  - |
    if [ `uname` = "Linux" ]
    then
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
      curl -sL https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh | sh -s .
    else
      echo 'skipping hlint/weeder...'
    fi
  - madlang install
  - madlang run demo/example.mad
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find . -name madlang -perm 755 | tail -n1)"
    else
      export BINPATH="$(find -name madlang -executable | tail -n2 | head -n1)"
    fi
  - echo $BINPATH
  - mv $BINPATH madlang-$TARGET
  - ls madlang-$TARGET

deploy:
  api_key:
    secure: "NeVULHPFKjRIvwrY1ewVXZo/LOKihKs1FQh2QU+s7jwgfT/d82cgQqmj0FJzT/cHmIkL+KhSJY5Nb+7kiwSyhH1qBCI3qNmGCkZ1oQsvosLnBu/s/nVhZ6CspbGTt3SxuumK0dRYyLDrKg4x4mFL/1QYU4bwr0N1moz3HZeI3Il0tu8Demse604hrMtCfAcs7uhaq+UN4y6hlBnWRgJup7fUrVgkihUQ+LQgOm1BeqozELjuRbgwJOuro3JdWYgLMTTF62+eQsMdYBUIJ6j3hpQ/YOjCankute/wHfGbbMOHsa5HLkSqhPMq8UB62potbKgLDC4C1P4q++i9mzgA6vwF/r42CQAwd05g/zuE4yjtNgMwjrS6gKuzONRFXMj1Dqm/AQFsnI8ecjHVm5Qh624xoskWZGm8L7gIeFPAhfngrhZZ+DJkEiHkmoGWigyiB9RO3m8nRaSDLyEZL733mnS+ufLjaUGXBoVymbx43wVbx91+4ZZgaSk7KkXOQlLSQx1/HyNPD/TL+LbrX0V4QI7zNcjgMEUmwnGV66H/diw2Hsg+OyS7rEA9QrEiLX5N/jQd9pw32WxqX5CgcoouRd1hgcIjq8b4koX+PXiz+GmjmbBNiJovV4saZpFHnsPEeTKZqkEp6bgMfHn9xPgObrT4fnCJUHozi6Txxfdv8Tc="
  file: madlang-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /\d+\.\d+\.\d+\.\d+.*$/
