sudo: false
cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc
addons:
    apt:
        packages:
            - cabal-install
            - ghc-8.0.2

before_install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal install cabal-install
- cabal install madlang --dependencies-only

install:
- cabal install madlang

script:
- madlang run demo/shakespeare.mad
