sudo: false
language: nix
cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc
addons:
    apt:
        packages:
            - zlib1g-dev
before_install:
- nix-env -i ghc
- nix-env -i cabal-install
- export PATH=$HOME/.cabal/bin:$PATH
- find / -name zlib.h
- cabal update
- cabal install madlang --dependencies-only

install:
- cabal install madlang

script:
- madlang run demo/shakespeare.mad
