sudo: false
language: nix
before_install:
- nix-env -i stack
- export PATH=$HOME/.local/bin:$PATH
- stack build --dependencies-only --install-ghc

install:
- stack install

script:
- madlang run demo/shakespeare.mad
