sudo: false
language: haskell
ghc: 8.0.2

#before_install:
#- nix-env -i stack
#- nix-env -i ghc
#- export PATH=$HOME/.local/bin:$PATH
#- stack build --dependencies-only --install-ghc
#- stack install cabal-install
#- cabal update

before_install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal new-build --dependencies-only -w ghc-8.0.2

install:
- cabal new-build -w ghc-8.0.2

script:
- madlang run demo/shakespeare.mad
- cabal new-test -w ghc-8.0.2
- cabal new-bench -w ghc-8.0.2
